---
deployment:
  tasks:
    - export DEPLOYPATH=/home/blootjmm/public_html
    - /bin/cp -R public/* $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer install --no-dev --working-dir=$DEPLOYPATH/..
    - cd $DEPLOYPATH/..
    - npm install
    - npm run build
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
